/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedSettingsRouteRouteImport } from './routes/(authenticated)/settings/route'
import { Route as authenticatedSettingsIndexRouteImport } from './routes/(authenticated)/settings/index'
import { Route as authenticatedSettingsProfileRouteImport } from './routes/(authenticated)/settings/profile'
import { Route as authenticatedSettingsPasswordRouteImport } from './routes/(authenticated)/settings/password'
import { Route as authenticatedSettingsAppearanceRouteImport } from './routes/(authenticated)/settings/appearance'

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedSettingsRouteRoute =
  authenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSettingsIndexRoute =
  authenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsProfileRoute =
  authenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsPasswordRoute =
  authenticatedSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)
const authenticatedSettingsAppearanceRoute =
  authenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => authenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/home': typeof authenticatedHomeRoute
  '/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/settings/password': typeof authenticatedSettingsPasswordRoute
  '/settings/profile': typeof authenticatedSettingsProfileRoute
  '/settings/': typeof authenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/home': typeof authenticatedHomeRoute
  '/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/settings/password': typeof authenticatedSettingsPasswordRoute
  '/settings/profile': typeof authenticatedSettingsProfileRoute
  '/settings': typeof authenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(authenticated)/settings': typeof authenticatedSettingsRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(authenticated)/settings/appearance': typeof authenticatedSettingsAppearanceRoute
  '/(authenticated)/settings/password': typeof authenticatedSettingsPasswordRoute
  '/(authenticated)/settings/profile': typeof authenticatedSettingsProfileRoute
  '/(authenticated)/settings/': typeof authenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/signup'
    | '/home'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/settings/appearance'
    | '/settings/password'
    | '/settings/profile'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(authenticated)/settings'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/(authenticated)/home'
    | '/(authenticated)/settings/appearance'
    | '/(authenticated)/settings/password'
    | '/(authenticated)/settings/profile'
    | '/(authenticated)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/settings': {
      id: '/(authenticated)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authenticatedSettingsRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/settings/': {
      id: '/(authenticated)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof authenticatedSettingsIndexRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/profile': {
      id: '/(authenticated)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof authenticatedSettingsProfileRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/password': {
      id: '/(authenticated)/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof authenticatedSettingsPasswordRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
    '/(authenticated)/settings/appearance': {
      id: '/(authenticated)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof authenticatedSettingsAppearanceRouteImport
      parentRoute: typeof authenticatedSettingsRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedSettingsRouteRouteChildren {
  authenticatedSettingsAppearanceRoute: typeof authenticatedSettingsAppearanceRoute
  authenticatedSettingsPasswordRoute: typeof authenticatedSettingsPasswordRoute
  authenticatedSettingsProfileRoute: typeof authenticatedSettingsProfileRoute
  authenticatedSettingsIndexRoute: typeof authenticatedSettingsIndexRoute
}

const authenticatedSettingsRouteRouteChildren: authenticatedSettingsRouteRouteChildren =
  {
    authenticatedSettingsAppearanceRoute: authenticatedSettingsAppearanceRoute,
    authenticatedSettingsPasswordRoute: authenticatedSettingsPasswordRoute,
    authenticatedSettingsProfileRoute: authenticatedSettingsProfileRoute,
    authenticatedSettingsIndexRoute: authenticatedSettingsIndexRoute,
  }

const authenticatedSettingsRouteRouteWithChildren =
  authenticatedSettingsRouteRoute._addFileChildren(
    authenticatedSettingsRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedSettingsRouteRoute: typeof authenticatedSettingsRouteRouteWithChildren
  authenticatedHomeRoute: typeof authenticatedHomeRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedSettingsRouteRoute: authenticatedSettingsRouteRouteWithChildren,
  authenticatedHomeRoute: authenticatedHomeRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
