FROM node:22-alpine AS base

# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Development stage
FROM base AS development
WORKDIR /app

# Copy workspace files
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages ./packages
COPY apps/api ./apps/api

# Install dependencies
# RUN pnpm install --frozen-lockfile
RUN pnpm install

WORKDIR /app/apps/api

EXPOSE 3001

CMD ["pnpm", "dev"]

